#!/bin/bash
fn=$2
function init {
    if [ -r $fn ]
    then
        if [ -a .$fn ]
        then
            if [ -d .$fn ]
            then
                echo "Repo already exists"
            else
                echo "File named .$2 exists"
            fi
        else
            mkdir .$fn
            echo "Creating zero revision"
            echo "-1" > ".$fn/count"
            touch ".$fn/HEAD"
            touch ".$fn/CUR_HEAD"
        fi
    else
        echo "$fn doesn't exist"
    fi
}
function check {
    if [ ! -r $fn ]
    then
        echo "$fn doesn't exist"
        exit 1
    fi
 
    if [ ! -d ".$fn" ]
    then
        echo "Repo doesn't exist"
        exit 2
    fi
 
    if [ ! -r ".$fn/count" ]
    then
        echo "Repo is broken"
        exit 3
    fi
}
function commit {
    check
   
    count=`cat .$fn/count`
    let "count=count+1"
    echo "$count" > ".$fn/count"
 
    diff -u ".$fn/HEAD" "$fn" > ".$fn/$count"
    cp $fn ".$fn/HEAD"
    cp $fn ".$fn/CUR_HEAD"
}
function status {
    check
   
    if diff $fn ".$fn/CUR_HEAD" > /dev/null ; 
    then
        echo "Status: stable"
        exit 1
    else
        echo "Status: modified"
        exit 2
    fi
}
function difference {
    check
   
    echo diff -u $fn ".$fn/HEAD"
}
function update {
    check
   
    cp ".$fn/HEAD" $fn
    revision=$1
    count=`cat .$fn/count`
    if [ $revision -gt $count ]  || [ 0 -gt $revision ]
    then
        echo "Wrong revision number"
        exit
    fi
    i=$count
 
    while [ $i -gt $revision ]
    do
        if [ ! -r ".$fn/$i" ]
        then
            echo "Repo is broken"
            exit
        fi
        patch -uR $fn ".$fn/$i"
        let "i=i-1"
    done
    cp $fn ".$fn/CUR_HEAD"
}
function remove {
    if [ -d ".$fn" ]
    then 
        rm -r .$fn
    fi
}
case $1 in
    'init')
        init
        ;;
    "commit")
        commit
        ;;
    "status")
        status
        ;;
    "diff")  
        difference
        ;;
    "update")
        update $3
        ;;
    "remove")
        remove
        ;;
    *)  
        echo "Incorrect command"
        ;;
esac